Feat/store
FIGHT-WORLD/Delivery_V1 pull request #5
Opened 2024-08-28 13:42 UTC by soy9

**Store**, **StoreCategory** 관련 api 구현했습니다.

현재 디테일한 부분에서 아직 수정할 사항이 남아있어서 미완 상태이며, 추후 기능 테스트 또한 진행할 예정입니다.
남은 사항도 빠르게 보완하겠습니다!

2024-08-28 14:09 UTC, wonowonow requested changes
와우,, 코드 진짜 깔끔하게 짜십니다.
제가 코멘트 남긴 부분 수정해서 다시 commit 해주시면 좋을 거 같습니다!

2024-08-28 14:09 UTC, wonowonow commented on src/main/java/com/fight_world/mono/domain/store/service/StoreServiceImpl.java
> +        storeRepository.save(store);
변경 감지를 사용하니, save 메서드를 사용하지 않는 것을 권장드립니다.
https://cindycho.tistory.com/74
save를 할 때 리소스를 절약할 수 있어요

2024-08-28 14:09 UTC, wonowonow commented on src/main/java/com/fight_world/mono/domain/store/service/StoreServiceImpl.java
> +            checkIsStoreOwner(userDetails, store);
저는 이 부분 많이 생각해봤는데, User, Admin api 를 따로 만들어서 필터딴에서만 걸러주는 게 더 좋을 거 같아요
그리고, 자기 자신 스토어 지우는 API 를 이용할때만 검증 로직을 타고요
제가 올린 Order Delete 메서드 한 번 확인해주시면 감사하겠습니다.

2024-08-28 14:09 UTC, wonowonow commented on src/main/java/com/fight_world/mono/domain/store_category/dto/response/StoreCategoryResponseDto.java
> +    public static StoreCategoryResponseDto of(StoreCategory storeCategory) {
유섭님이 저한테 코멘트 달아주신 것처럼
매개변수 한개면 from, 여러개면 of 를 쓰는 걸로 통일하면 좋을 거 같아용

2024-08-28 14:09 UTC, wonowonow commented on src/main/java/com/fight_world/mono/domain/store_category/service/StoreCategoryServiceImpl.java
> +public class StoreCategoryServiceImpl implements StoreCategoryService {
이 서비스 코드들 트랜잭션 어노테이션이 전부 빠져 있습니다.
넣어주시면 될 거 같아용

2024-08-28 14:09 UTC, wonowonow commented on src/main/java/com/fight_world/mono/domain/store/model/Store.java
> +    public void deleteStore(Long deletedByUserId) {
제가 올린 timebase 에 delete 함수 쓰시면 좋을 거 같습니다.

2024-08-29 01:20 UTC, soy9 commented on src/main/java/com/fight_world/mono/domain/store/service/StoreServiceImpl.java
> +        storeRepository.save(store);
아하 맞네요 변경감지.. 확인해주셔서 감사합니다!
수정하겠습니다

2024-08-29 03:00 UTC, shin3766 commented on src/main/java/com/fight_world/mono/domain/store/service/StoreServiceImpl.java
> +            checkIsStoreOwner(userDetails, store);
저도 같은 생각입니다. 
필터링 할때 아예 /api/v1/admin 이렇게 해서 admin용 api를 만드는게 좋아보이네요
이따가 회의시간때 한번 논의해봐요

2024-08-29 03:50 UTC, wonowonow approved these changes
고생하셨습니다!

2024-08-29 03:50 UTC, merged